### ISSUE TITLE
Automatically fetch data from Pretalx

### ISSUE THREAD

**Issue by travigd** [JuliaCon/juliacon-webapp#35]
Pretalx data can be updated by conference speakers at their leisure. It'd be nice to automate fetching that and making a PR using GitHub actions.

[Something like this](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#spider-and-download-a-website):
```yaml
name: Download Website
on:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download website
        run: |
          wget \
            --recursive \
            --level=2 \
            --wait=1 \
            --no-clobber \
            --page-requisites \
            --html-extension \
            --convert-links \
            --domains quotes.toscrape.com \
            http://quotes.toscrape.com/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: update local website copy
          title: Automated Updates to Local Website Copy
          body: This is an auto-generated PR with website updates.
          branch: website-updates
```
